---
services:
#-----------------------------------------------
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
    ports:
      - 8443:8443 # HTTPS
      - 8123:8123 # DYNMAP
      - 19132:19132/udp # BEDROCK
      - 25565-25570:25565-25570 # MC SERV PORT RANGE
    volumes:
      - ${CONFIG_PATH}/crafty/backups:/crafty/backups
      - ${CONFIG_PATH}/crafty/logs:/crafty/logs
      - ${CONFIG_PATH}/crafty/servers:/crafty/servers
      - ${CONFIG_PATH}/crafty/config:/crafty/app/config
      - ${CONFIG_PATH}/crafty/import:/crafty/import
    restart: unless-stopped
    stop_grace_period: 2m
    networks:
      dmz_mac_vlan:
        ipv4_address: 192.168.215.131
      general_brg:
#-----------------------------------------------
  valheim:
    container_name: valheim
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - ${CONFIG_PATH}/valheim/config:/config
      - ${CONFIG_PATH}/valheim/data:/opt/valheim
    #ports: !non needed in macvlan!
      #- 2456-2458:2456-2458/udp
      #- 9001:9001/tcp
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
      - SERVER_NAME=${VALHEIMSRNAME}
      - WORLD_NAME=${VALHEIMWORLDNAME}
      - SERVER_PASS=${VALHEIMSRPASS}
      - SERVER_PUBLIC=false
      - SERVER_ARGS=-crossplay
    restart: unless-stopped
    stop_grace_period: 2m
    networks:
      dmz_mac_vlan:
        ipv4_address: 192.168.215.132
#-----------------------------------------------
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ${DOCKERCONFIGPATH}/ollama:/root/.ollama  # Store models persistently
    networks:
      - llm_stack
#-----------------------------------------------
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - 3000:3000
      - 8080:8080
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_BASE_URL=http://localhost:11434
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ${DOCKERCONFIGPATH}/openwebui/data:/app/backend/data  # Store WebUI data persistently
    networks:
      - llm_stack
#-----------------------------------------------
  homebridge:
    image: homebridge/homebridge:ubuntu
    container_name: homebridge
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ${CONFIG_PATH}/homebridge:/homebridge
    networks:
        service_mac_vlan:
          ipv4_address: 192.168.213.134
#-----------------------------------------------
  traefik:
    image: docker.io/library/traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ${DOCKERCONFIGPATH}/traefik/data/certs/cloudflare-acme.json:/var/traefik/certs/cloudflare-acme.json:rw
      - ${DOCKERCONFIGPATH}/traefik/data/certs/:/var/traefik/certs/:rw
      - ${DOCKERCONFIGPATH}/traefik/config/conf.d/:/etc/traefik/conf.d/:ro
    environment:
      - CF_DNS_API_TOKEN=${NEW_DOMAIN_DNS_EDIT_CF}
    restart: unless-stopped
    networks:
      traefik_default:
        ipv4_address: 172.25.0.2
#-----------------------------------------------
  slash:
    image: yourselfhosted/slash:latest
    container_name: slash
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
    #ports:
      #- 5231:5231
    networks:
      dmz_mac_vlan:
        ipv4_address: 192.168.215.133
    volumes:
      - ${CONFIG_PATH}/slash:/var/opt/slash
    restart: unless-stopped
#-----------------------------------------------
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - ${CONFIG_PATH}/rustdesk-hbbs:/root
    networks:
      dmz_mac_vlan:
        ipv4_address: 192.168.215.136
    depends_on:
      - hbbr
    restart: unless-stopped
  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ${CONFIG_PATH}/rustdesk-hbbr:/root
    networks:
      dmz_mac_vlan:
        ipv4_address: 192.168.215.135
    restart: unless-stopped
#-----------------------------------------------
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    network_mode: "service:gluetun"
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
    volumes:
      - ${DOCKERCONFIGPATH}/Lidarr/config:/config
      - ${DOWNLOADSPATH}/downloads/media/audio/music:/music
      - ${DOWNLOADSPATH}/downloads:/downloads
    restart: unless-stopped
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: "curl -sf https://example.com  || exit 1"
      interval: 1m
      timeout: 10s
      retries: 1
    labels:
      deunhealth.restart.on.unhealthy: true
#-----------------------------------------------
  slskd:
    image: slskd/slskd
    container_name: slskd
    network_mode: "service:gluetun"
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_FILE_PERMISSION_MODE=777
      - SLSKD_SLSK_USERNAME=${SLSKUSR}
      - SLSKD_SLSK_PASSWORD=${SLSKPASS}
      - SLSKD_DOWNLOADS_DIR=/downloads/slskd/complete
      - SLSKD_INCOMPLETE_DIR=/downloads/slskd/working
      - SLSKD_SHARED_DIR=/music
      - SLSKD_USERNAME=${SLSKUSR}
      - SLSKD_PASSWORD=${SLSKPASS}
      - SLSKD_SLSK_LISTEN_PORT=5032
    volumes:
      - ${DOCKERCONFIGPATH}/slskd/config:/app
      - ${DOWNLOADSPATH}/downloads/media/audio/music:/music
      - ${DOWNLOADSPATH}/downloads/downloads:/downloads
    restart: unless-stopped
#-----------------------------------------------
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
    volumes:
      - ${CONFIG_PATH}/tautulli/config:/config
      - ${CONFIG_PATH}/pms/config/Library/Application Support/Plex Media Server/Logs:/pms-logs
    restart: always
    networks:
      general_brg:
      vpn_stack_brg:
#-----------------------------------------------
  privatebin:
    image: "privatebin/nginx-fpm-alpine:stable"
    container_name: privatebin
    read_only: true
    networks:
      dmz_mac_vlan:
        ipv4_address: 192.168.215.133
    restart: always
    volumes:
      - privatebin_cfg:/srv/data
      - /dev/shm:/var/lib/nginx/tmp
#-----------------------------------------------
  speedtest:
      restart: unless-stopped
      container_name: openspeedtest
      environment:
        - PUID=568
        - PGID=568
        - TZ=${TZ}
      ports:
        - '3000:3000'
        - '3001:3001'
      image: openspeedtest/latest
      networks:
        general_brg:
#-----------------------------------------------
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
        general_brg:
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 1m
      timeout: 10s
      retries: 3
#-----------------------------------------------
volumes:
    privatebin_cfg:
#-----------------------------------------------
networks:
  llm_stack:
    driver: bridge
  dmz_mac_vlan:
    external: true
  service_mac_vlan:
    external: true
  general_brg:
    external: true
  vpn_stack_brg:
    external: true
  traefik_default:
    external: false
    driver: bridge
    ipam:
     config:
       - subnet: 172.25.0.0/16
         gateway: 172.25.0.1
