use_default_settings:
  engines:
    keep_only:
      - bing
      - brave
      - duckduckgo
      - google
      - wikipedia

general:
  debug: false
  instance_name: AI Tools Private Search
  enable_metrics: false

search:
  safe_search: 1
  autocomplete: ""
  default_lang: en
  formats:
    - json
  ban_time_on_fail: 30
  max_ban_time_on_fail: 3600

server:
  port: 8080
  bind_address: 0.0.0.0
  base_url: http://searxng:8080/
  limiter: false
  public_instance: false
  image_proxy: false
  method: GET

ui:
  query_in_title: false
  default_locale: en

outgoing:
  request_timeout: 5.0
  max_request_timeout: 15.0
  pool_connections: 20
  pool_maxsize: 10
  enable_http2: true
  extra_proxy_timeout: 2
  proxies:
    all://:
      - http://research-egress:3128
