---
services:
#---------------------------------------------------
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    ports:
      - 8083:8080
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      general_default:
        ipv4_address: 172.26.0.2
#----------------------------------------------------------
    plex:
      container_name: plex
      image: plexinc/pms-docker
      restart: unless-stopped
      runtime: nvidia
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - PLEX_CLAIM=${PMSCLAIM}
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      network_mode: host
      volumes:
        - ${DOCKERCONFIGPATH}/pms/config:/config
        - /dev/shm:/transcode
        - ${MEDIAPATH}:/media