services:
#-----------------------------------------------
  valheim:
    container_name: valheim
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - ${CONFIG_PATH}/valheim/config:/config
      - ${CONFIG_PATH}/valheim/data:/opt/valheim
    #ports: !non needed in macvlan!
      #- 2456-2458:2456-2458/udp
      #- 9001:9001/tcp
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
      - SERVER_NAME=${VALHEIMSRNAME}
      - WORLD_NAME=${VALHEIMWORLDNAME}
      - SERVER_PASS=${VALHEIMSRPASS}
      - SERVER_PUBLIC=false
      - SERVER_ARGS=-crossplay
    restart: unless-stopped
    stop_grace_period: 2m
    networks:
      dmz_mac_vlan:
        ipv4_address: 192.168.215.132
#-----------------------------------------------
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
    ports:
        - 8443:8443 # HTTPS
        - 8123:8123 # DYNMAP
        - 19132:19132/udp # BEDROCK
        - 25565-25570:25565-25570 # MC SERV PORT RANGE
    volumes:
        - ${CONFIG_PATH}/crafty-4/backups:/crafty/backups
        - ${CONFIG_PATH}/crafty-4/logs:/crafty/logs
        - ${CONFIG_PATH}/crafty-4/servers:/crafty/servers
        - ${CONFIG_PATH}/crafty-4/config:/crafty/app/config
        - ${CONFIG_PATH}/crafty-4/import:/crafty/import
    restart: unless-stopped
    stop_grace_period: 2m
    networks:
      dmz_mac_vlan:
        ipv4_address: 192.168.215.131
#-----------------------------------------------
networks:
    dmz_mac_vlan:
      external: true
    service_mac_vlan:
      external: true
    general_brg:
      external: true
    vpn_stack_brg:
      external: true
