services:
#-----------------------------------------------
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
    ports:
        - 8443:8443 # HTTPS
        - 8123:8123 # DYNMAP
        - 19132:19132/udp # BEDROCK
        - 25565-25570:25565-25570 # MC SERV PORT RANGE
    volumes:
        - ${CONFIG_PATH}/crafty/backups:/crafty/backups
        - ${CONFIG_PATH}/crafty/logs:/crafty/logs
        - ${CONFIG_PATH}/crafty/servers:/crafty/servers
        - ${CONFIG_PATH}/crafty/config:/crafty/app/config
        - ${CONFIG_PATH}/crafty/import:/crafty/import
    restart: unless-stopped
    stop_grace_period: 2m
    networks:
      dmz_mac_vlan:
        ipv4_address: 192.168.215.131
#-----------------------------------------------
networks:
    dmz_mac_vlan:
      external: true
    service_mac_vlan:
      external: true
    general_brg:
      external: true
    vpn_stack_brg:
      external: true
