---
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    command: >
      sh -c "ollama pull deepseek-r1:8b && ollama run deepseek-r1:8b"
    ports:
      - "11434:11434"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ${DOCKERCONFIGPATH}/ollama:/root/.ollama  # Store models persistently
    networks:
      - llm_stack
#-----------------------------------------------
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - 3000:3000
      - 8080:8080
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_BASE_URL=http://localhost:11434
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ${DOCKERCONFIGPATH}/openwebui/data:/app/backend/data  # Store WebUI data persistently
    networks:
      - llm_stack
#-----------------------------------------------
networks:
  llm_stack:
    driver: bridge