---
services:
  traefik:
    image: docker.io/library/traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ${DOCKERCONFIGPATH}/traefik/data/certs/cloudflare-acme.json:/var/traefik/certs/cloudflare-acme.json:rw
      - ${DOCKERCONFIGPATH}/traefik/data/certs/:/var/traefik/certs/:rw
      - ${DOCKERCONFIGPATH}/traefik/config/conf.d/:/etc/traefik/conf.d/:ro
    environment:
      - CF_DNS_API_TOKEN=${NEW_DOMAIN_DNS_EDIT_CF}
    restart: unless-stopped
    networks:
      traefik_default:
        ipv4_address: 172.25.0.2
#-----------------------------------------------
networks:
  traefik_default:
    external: false
    driver: bridge
    ipam:
     config:
       - subnet: 172.25.0.0/16
         gateway: 172.25.0.1
