services:
#-----------------------------------------------
  npm:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    networks:
      general_brg:
      vpn_stack_brg:
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFIGPATH}/npm/config:/data
      - ${DOCKERCONFIGPATH}/npm/le:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 120s
      timeout: 3s
      retries: 3
#-----------------------------------------------
  cloudflared: 
    image: cloudflare/cloudflared 
    container_name: cloudflare-tunnel
    restart: always 
    networks:
      general_brg:
    command: tunnel run 
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
#-----------------------------------------------
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    environment:
      - TZ=${TZ}
      - PORT=5055
    networks:
      vpn_stack_brg:
      general_brg:
    ports:
      - 5055:5055
    volumes:
      - ${DOCKERCONFIGPATH}/overseerr:/app/config
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1"
      start_period: 20s
      interval: 15s
      timeout: 3s
      retries: 3
#-----------------------------------------------
networks:
    general_brg:
      external: true
    vpn_stack_brg:
      external: true
    
