services:
#-----------------------------------------------
  npm:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    networks:
      general_brg:
      vpn_stack_brg:
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFIGPATH}/npm/config:/data
      - ${DOCKERCONFIGPATH}/npm/le:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 120s
      timeout: 3s
      retries: 3
#-----------------------------------------------
  cloudflared: 
    image: cloudflare/cloudflared 
    container_name: cloudflare-tunnel
    restart: always 
    networks:
      general_brg:
    command: tunnel run 
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
#-----------------------------------------------
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      vpn_stack_brg:
      general_brg:
    ports:
      - 5055:5055
    volumes:
      - ${DOCKERCONFIGPATH}/overseerr:/config
    restart: unless-stopped
    healthcheck:
      test: "curl --fail http://localhost:5055/api/v1/status || exit 1"
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
#-----------------------------------------------
networks:
    general_brg:
      external: true
    vpn_stack_brg:
      external: true
    
