services:
  mongodb:
    image: "mongo:7.0"
    restart: "on-failure"
    networks:
      - graylog_brg
    volumes:
      - ${DOCKERCONFIGPATH}/mongodb_data:/data/db
      - ${DOCKERCONFIGPATH}/mongodb_config:/data/configdb
#-----------------------------------------------
  datanode:
    image: "${DATANODE_IMAGE:-graylog/graylog-datanode:6.3}"
    hostname: "datanode"
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      GRAYLOG_DATANODE_PASSWORD_SECRET: ${GRAYLOGSECRET}
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8999:8999/tcp"
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    networks:
      - graylog_brg
    volumes:
      - datanode_data:/var/lib/graylog-datanode
    restart: "on-failure"
#-----------------------------------------------
  graylog:
    hostname: "server"
    image: "${GRAYLOG_IMAGE:-graylog/graylog:6.3}"
    depends_on:
      mongodb:
        condition: service_started
      datanode:
        condition: service_started
    entrypoint: "/usr/bin/tini -- /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      GRAYLOG_PASSWORD_SECRET: ${GRAYLOGSECRET}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${ADMINPASSSHA2}
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
      - "5044:5044/tcp"
      - "5140:5140/tcp"
      - "5140:5140/udp"
      - "5555:5555/tcp"
      - "5555:5555/udp"
      - "9000:9000/tcp"
      - "12201:12201/tcp"
      - "12201:12201/udp"
      - "13301:13301/tcp"
      - "13302:13302/tcp"
    networks:
      - graylog_brg
    volumes:
      - graylog_data:/usr/share/graylog/data/data
    restart: "on-failure"
#-----------------------------------------------
networks:
  graylog_brg:
    external: true
volumes:
  datanode_data:
  graylog_data: