---
services:
#-----------------------------------------------
    plex:
      image: lscr.io/linuxserver/plex:latest
      container_name: plex
      restart: always
      environment:
        - PUID=568
        - PGID=568
        - TZ=Europe/London
        - PLEX_CLAIM=${PLEX_CLAIM}
      volumes:
        - ${CONFIG_PATH}/pms:/config
        - ${MEDIA_PATH}:/library
        - /dev/shm:/transcode
      devices:
        - /dev/dri:/dev/dri
      network_mode: host
      #networks:
        #general_brg:
#-----------------------------------------------
networks:
    general_brg:
      external: true
    vpn_stack_brg:
      external: true
