---
services:
#-----------------------------------------------
    plex:
      image: lscr.io/linuxserver/plex:latest
      container_name: plex
      restart: always
      environment:
        - PUID=568
        - PGID=568
        - TZ=Europe/London
        - PLEX_CLAIM=${PLEX_CLAIM}
      volumes:
        - type: bind
          source: ${CONFIG_PATH}/pms
          target: /config
          bind:
            create_host_path: false
        - type: bind
          source: ${MEDIA_PATH}
          target: /library
          bind:
            create_host_path: false
        - type: bind
          source: /dev/shm
          target: /transcode
          bind:
            create_host_path: false
      devices:
        - /dev/dri:/dev/dri
      network_mode: host
      #networks:
        #general_brg:
#-----------------------------------------------
networks:
    general_brg:
      external: true
    vpn_stack_brg:
      external: true
