services:
#-----------------------------------------------
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "109" #for iGPU access
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFIGPATH}/frigate/config:/config
      - ${DOCKERCONFIGPATH}/frigate/media:/media/frigate
      - ${DOCKERCONFIGPATH}/frigate/models:/models
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    networks:
        general_brg:
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - FRIGATE_RTSP_PASSWORD=${FRIGATE_RTSP_PASSWORD}
      - TZ=${TZ:-UTC}
    healthcheck:
      test: "curl -f http://localhost:5000/api/version || exit 1"
      interval: 1m
      timeout: 10s
      retries: 3
#-----------------------------------------------
  birdnet-go:
    image: ghcr.io/tphakala/birdnet-go:nightly
    container_name: birdnet-go
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-8080}:8080"
    networks:
        general_brg:
    environment:
      - TZ=${TZ:-UTC}
      - BIRDNET_UID=568
      - BIRDNET_GID=568
      # BirdNET Configuration
      - BIRDNET_LOCALE=en-uk                      # Locale code (2-10 chars, e.g., "en" or "en-us")
      - BIRDNET_LATITUDE=${loclat}                 # Valid range: -90.0 to 90.0
      - BIRDNET_LONGITUDE=${loclong}              # Valid range: -180.0 to 180.0
      - BIRDNET_SENSITIVITY=1.0                   # Valid range: 0.1 to 1.5 (higher = more sensitive)
      - BIRDNET_THRESHOLD=0.7                     # Valid range: 0.0 to 1.0 (confidence threshold)
      - BIRDNET_OVERLAP=1.5                       # Valid range: 0.0 to 2.9 seconds (audio chunk overlap)
      - BIRDNET_THREADS=0                         # 0 = auto (use all CPUs), or specify number of threads
      - BIRDNET_DEBUG=false                       # Enable debug logging (true/false)
      - BIRDNET_USEXNNPACK=true                   # Use XNNPACK acceleration (true/false)
      # Range Filter Configuration               
      - BIRDNET_RANGEFILTER_MODEL=latest
      - BIRDNET_RANGEFILTER_THRESHOLD=0.01
    healthcheck:
      test: "curl -f http://localhost:8080/ || exit 1"
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - ${DOCKERCONFIGPATH}/birdnet-go/config:/config
      - ${DOCKERCONFIGPATH}/birdnet-go/data:/data
    tmpfs:
      - /config/hls:exec,size=50M,uid=${BIRDNET_UID:-568},gid=${BIRDNET_GID:-568},mode=0755
#-----------------------------------------------
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ${DOCKERCONFIGPATH}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - general_brg
    ports:
      - "8123:8123"
    healthcheck:
      test: "curl -f http://localhost:8123/manifest.json || exit 1"
      interval: 1m
      timeout: 10s
      retries: 3
#-----------------------------------------------
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    user: "568:568"
    environment:
      - TZ=${TZ:-UTC}
    networks:
      - general_brg
    ports:
      - "5580:5580"
      - "5540:5540"
    volumes:
      - ${DOCKERCONFIGPATH}/matter-server/data:/data:rw
      - /run/dbus:/run/dbus:ro
#-----------------------------------------------
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    user: "568:568"
    environment:
      - TZ=${TZ:-UTC}
    networks:
      - general_brg
    ports:
      - "1883:1883"
    volumes:
      - ${DOCKERCONFIGPATH}/mosquitto/config:/mosquitto/config
      - ${DOCKERCONFIGPATH}/mosquitto/data:/mosquitto/data
      - ${DOCKERCONFIGPATH}/mosquitto/log:/mosquitto/log
#-----------------------------------------------
  yawamf-backend:
    image: ghcr.io/jellman86/wamf-backend:dev
    container_name: yawamf-backend
    restart: unless-stopped
    user: "568:568"
    networks:
      general_brg:
    volumes:
      - ${DOCKERCONFIGPATH}/YA-WAMF/config:/config        # Configuration files (config.json)
      - ${DOCKERCONFIGPATH}/YA-WAMF/data:/data            # Persistent data (database, models)
    ports:
      - "8946:8000"
    environment:
      - TZ=${TZ:-UTC}
      - FRIGATE__FRIGATE_URL=${FRIGATE_URL:-http://frigate:5000}
      - FRIGATE__FRIGATE_AUTH_TOKEN=${FRIGATE_AUTH_TOKEN:-}
      - FRIGATE__MQTT_SERVER=${MQTT_SERVER:-mqtt}
      - FRIGATE__MQTT_PORT=${MQTT_PORT:-1883}
      - FRIGATE__MQTT_AUTH=${MQTT_AUTH:-false}
      - FRIGATE__MQTT_USERNAME=${MQTT_USERNAME:-}
      - FRIGATE__MQTT_PASSWORD=${MQTT_PASSWORD:-}
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--timeout-keep-alive", "75"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
#----------------
  yawamf-frontend:
    image: ghcr.io/jellman86/wamf-frontend:dev
    container_name: yawamf-frontend
    restart: unless-stopped
    user: "568:568"
    networks:
      general_brg:
    ports:
      - "9852:80"
    depends_on:
      - yawamf-backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 3
#-----------------------------------------------
networks:
    general_brg:
      external: true