[accounts.icloud]
default = true
email = "${ICLOUD_EMAIL}"
display-name = "${ICLOUD_DISPLAY_NAME}"

backend.type = "imap"
backend.host = "imap.mail.me.com"
backend.port = 993
backend.encryption.type = "tls"
backend.login = "${ICLOUD_IMAP_LOGIN}"
backend.auth.type = "password"
backend.auth.cmd = "cat /run/secrets/icloud_app_password"

folder.aliases.inbox = "INBOX"
folder.aliases.sent = "Sent Messages"
folder.aliases.drafts = "Drafts"
folder.aliases.trash = "Deleted Messages"
