services:
#-----------------------------------------------
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    user: "568:568"
    environment:
        - TZ=Europe/London
    volumes:
      - ${CONFIG_PATH}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
        service_mac_vlan:
          ipv4_address: 192.168.213.142
#-----------------------------------------------
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    user: "568:568"
    environment:
      - TZ=Europe/London
    # Host networking is strongly recommended
    networks:
        service_mac_vlan:
          ipv4_address: 192.168.213.143
    # If you cannot use host mode, expose 5580 and ensure IPv6 + mDNS are OK:
    # ports:
    #   - "5580:5580"
    #   - "5540:5540"  # (commissioning API port; often not needed externally)
    volumes:
      - ${CONFIG_PATH}/matter-server/data:/data:rw
      - /run/dbus:/run/dbus:ro  # optional (BLE commissioning on some setups)
#-----------------------------------------------
networks:
    service_mac_vlan:
      external: true
    general_brg:
      external: true
    vpn_stack_brg:
      external: true