services:
#-----------------------------------------------
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
        - PUID=568
        - PGID=568
        - TZ=Europe/London
    volumes:
      - ${CONFIG_PATH}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
        service_mac_vlan:
          ipv4_address: 192.168.213.142
#-----------------------------------------------
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
    # Host networking is strongly recommended
    networks:
        service_mac_vlan:
          ipv4_address: 192.168.213.143
    # If you cannot use host mode, expose 5580 and ensure IPv6 + mDNS are OK:
    # ports:
    #   - "5580:5580"
    #   - "5540:5540"  # (commissioning API port; often not needed externally)
    volumes:
      - ${CONFIG_PATH}/matter-server/data:/data:rw
      - /run/dbus:/run/dbus:ro  # optional (BLE commissioning on some setups)
#-----------------------------------------------
  mosquitto:
    image: lscr.io/linuxserver/mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    #ports:
      #- "1883:1883"
      #- "9001:9001"
    environment:
        - PUID=568
        - PGID=568
        - TZ=Europe/London
    volumes:
      - ${CONFIG_PATH}/mosquitto/config:/mosquitto/config
      - ${CONFIG_PATH}/mosquitto/data:/mosquitto/data
      - ${CONFIG_PATH}/mosquitto/log:/mosquitto/log
    networks:
        service_mac_vlan:
          ipv4_address: 192.168.213.141
#-----------------------------------------------
  zigbee2mqtt:
    image: lscr.io/linuxserver/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    restart: unless-stopped
    #ports:
      #- "8080:8080"
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://mosquitto:1883
      - ZIGBEE2MQTT_CONFIG_MQTT_USER=ha
      - ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD=myStrongPass
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=/dev/serial/by-id/usb-YourRadioHere
      - ZIGBEE2MQTT_CONFIG_FRONTEND=true
    volumes:
      - ${CONFIG_PATH}/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    #devices:
      #- /dev/serial/by-id/usb-YourRadioHere:/dev/serial/by-id/usb-YourRadioHere
    networks:
        service_mac_vlan:
          ipv4_address: 192.168.213.140
#-----------------------------------------------
  esphome:
    image: esphome/esphome:latest
    container_name: esphome
    restart: unless-stopped
    #ports:
      #- "6052:6052"
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
    volumes:
      - ${CONFIG_PATH}/apps/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
        service_mac_vlan:
          ipv4_address: 192.168.213.139
#-----------------------------------------------
  nodered:
    Image: lscr.io/linuxserver/node-red:latest
    container_name: nodered
    restart: unless-stopped
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/London
    #ports:
      #- "1880:1880"
    volumes:
      - ${CONFIG_PATH}/nodered/data:/data
    networks:
        service_mac_vlan:
          ipv4_address: 192.168.213.138
#-----------------------------------------------
networks:
    service_mac_vlan:
      external: true
    general_brg:
      external: true
    vpn_stack_brg:
      external: true